# Generated by Django 3.2.7 on 2022-01-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gstbillingapp', '0011_auto_20200609_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_amt_paid',
            field=models.FloatField(default=0),
        ),
    ]
